/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import communication.Communication;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Clan;
import model.Iznajmljivanje;

/**
 *
 * @author kacan
 */
public class FrmClanGlavna extends javax.swing.JFrame {

    Communication communication;
    List<Iznajmljivanje> iznajmljivanja;
    Clan ulogovani;

    /**
     * Creates new form FrmClanGlavna
     */
    public FrmClanGlavna(Clan ulogovani) {
        communication = Communication.getInstance();
        this.ulogovani = ulogovani;
        initComponents();
        popuniPoljaClana();
        dobaviIznajmljivanja();
        System.out.println(iznajmljivanja);
        if (iznajmljivanja.isEmpty()) {
            prikazBezIznajmljivanja();
        } else {
            prikazSaIznajmljivanjima();
        }
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblIme = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPrezime = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblDatumUclanjenja = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblDatumIstekaClanarine = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTrajanjeClanarine = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblBrojTrenutnihKnjiga = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblTipClanstva = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblIznajmljivanja = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        btnPrikaziDetalje = new javax.swing.JButton();
        lblNemaIznajmljivanja = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Moji podaci");

        jLabel2.setText("Ime:");

        lblIme.setText("NekoIme");

        jLabel3.setText("Prezime:");

        lblPrezime.setText("Neko prezime");

        jLabel4.setText("Email:");

        lblEmail.setText("nekiemail@gmail.com");

        jLabel5.setText("Datum učlanjenja:");

        lblDatumUclanjenja.setText("07.10.2002");

        jLabel6.setText("Datum isteka članarine:");

        lblDatumIstekaClanarine.setText("Nikad.");

        jLabel7.setText("Preostalo trajanje članarine (u mesecima):");

        lblTrajanjeClanarine.setText("12");

        jLabel8.setText("Broj knjiga koje su trenutno kod Vas:");

        lblBrojTrenutnihKnjiga.setText("7");

        jLabel9.setText("Tip članstva:");

        lblTipClanstva.setText("Počasni");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tblIznajmljivanja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblIznajmljivanja);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Moja iznajmljivanja");

        btnPrikaziDetalje.setText("Prikaži detalje o izabranom iznajmljivanju");
        btnPrikaziDetalje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziDetaljeActionPerformed(evt);
            }
        });

        lblNemaIznajmljivanja.setText("Jošuvek nemate iznajmljivanja.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIme))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrezime))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEmail))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDatumUclanjenja))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDatumIstekaClanarine))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTrajanjeClanarine))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBrojTrenutnihKnjiga))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTipClanstva)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrikaziDetalje)
                    .addComponent(lblNemaIznajmljivanja))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblIme))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblPrezime))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblDatumUclanjenja))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblDatumIstekaClanarine))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblTrajanjeClanarine))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblBrojTrenutnihKnjiga))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblTipClanstva)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNemaIznajmljivanja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrikaziDetalje)))
                .addContainerGap(204, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrikaziDetaljeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziDetaljeActionPerformed
        int izbor = tblIznajmljivanja.getSelectedRow();
        if (izbor == -1) {
            JOptionPane.showMessageDialog(this, "Morate da selektujte iznajmljivanje iz tabele.", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }

        TableModelIznajmljivanje model = (TableModelIznajmljivanje) tblIznajmljivanja.getModel();
        Iznajmljivanje izabranoIznajmljivanje = model.getIznajmljivanje(izbor);

        FrmPrikazIznajmljivanja frm = new FrmPrikazIznajmljivanja(izabranoIznajmljivanje);
        frm.setVisible(true);
        frm.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnPrikaziDetaljeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrikaziDetalje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBrojTrenutnihKnjiga;
    private javax.swing.JLabel lblDatumIstekaClanarine;
    private javax.swing.JLabel lblDatumUclanjenja;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblIme;
    private javax.swing.JLabel lblNemaIznajmljivanja;
    private javax.swing.JLabel lblPrezime;
    private javax.swing.JLabel lblTipClanstva;
    private javax.swing.JLabel lblTrajanjeClanarine;
    private javax.swing.JTable tblIznajmljivanja;
    // End of variables declaration//GEN-END:variables

    private void dobaviIznajmljivanja() {
        List<Iznajmljivanje> SvaIznajmljivanja = communication.vratiSvaIznajmljivanja();
        iznajmljivanja = new ArrayList<>();
        for (Iznajmljivanje iznajmljivanje : SvaIznajmljivanja) {

            if (iznajmljivanje.getClan().getIdClan() == ulogovani.getIdClan()) {
                iznajmljivanja.add(iznajmljivanje);
            }
        }
    }

    private void prikazBezIznajmljivanja() {
        jScrollPane2.setVisible(false);  
        tblIznajmljivanja.setVisible(false);
        btnPrikaziDetalje.setVisible(false);
        lblNemaIznajmljivanja.setVisible(true); 
    }

    private void prikazSaIznajmljivanjima() {
        TableModelIznajmljivanje modelIznajmljivanje = new TableModelIznajmljivanje(iznajmljivanja);
        tblIznajmljivanja.setModel(modelIznajmljivanje);
        lblNemaIznajmljivanja.setVisible(false);
    }

    private void popuniPoljaClana() {
        lblIme.setText(ulogovani.getIme());
        lblPrezime.setText(ulogovani.getPrezime());
        lblEmail.setText(ulogovani.getEmail());
        lblDatumUclanjenja.setText(ulogovani.getDatumUclanjenja().format(DateTimeFormatter.ofPattern("dd.MM.yyyy")));
        lblDatumIstekaClanarine.setText(ulogovani.getDatumIstekaClanarine().format(DateTimeFormatter.ofPattern("dd.MM.yyyy")));
        lblTrajanjeClanarine.setText(String.valueOf(ulogovani.getTrajanjeClanarine()));
        lblBrojTrenutnihKnjiga.setText(String.valueOf(ulogovani.getBrTrenutnihKnjiga()));
        lblTipClanstva.setText(ulogovani.getTipClanstva().toString());
    }
}
