/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import communication.Communication;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JFrame;
import model.Iznajmljivanje;
import model.StavkaIznajmljivanja;

/**
 *
 * @author kacan
 */
public class FrmPrikazIznajmljivanja extends javax.swing.JFrame {

    Communication communication;
    private List<StavkaIznajmljivanja> stavkeIznajmljivanja;
    Iznajmljivanje izabranoIznajmljivanje;

    /**
     * Creates new form FrmPrikazIznajmljivanja
     *
     * @param izabranoIznajmljivanje
     */
    public FrmPrikazIznajmljivanja(Iznajmljivanje izabranoIznajmljivanje) {
        this.izabranoIznajmljivanje = izabranoIznajmljivanje;
        communication = Communication.getInstance();
        setTitle("Detalji iznajmljivanja");

        initComponents();
        ucitajStavkeIznajmljivanja();
        if (stavkeIznajmljivanja != null) {
            popuniTabelu();
        }
        popuniOstalaPolja();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblBibliotekar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStavkeIznajmljivanja = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblDatumIznajmljivanja = new javax.swing.JLabel();
        lblRokVracanja = new javax.swing.JLabel();
        lblBrStavki = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bibliotekar:");

        lblBibliotekar.setText("Ime bibliotekara");

        jLabel3.setText("Datum iznajmljivanja:");

        jLabel4.setText("Rok vracanja:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Knjige dodate u iznajmljivanje");

        tblStavkeIznajmljivanja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Knjiga", "Napomena"
            }
        ));
        jScrollPane2.setViewportView(tblStavkeIznajmljivanja);

        jLabel10.setText("Broj stavki iznajmljivanja: ");

        jLabel11.setText("Status:");

        lblDatumIznajmljivanja.setText("Neki datum");

        lblRokVracanja.setText("Neki datum opet");

        lblBrStavki.setText("Neki broj");

        lblStatus.setText("Neki status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(630, 630, 630))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblStatus))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblBrStavki))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDatumIznajmljivanja))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblBibliotekar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblRokVracanja)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2)
                            .addComponent(jSeparator1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblBibliotekar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblDatumIznajmljivanja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblRokVracanja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblBrStavki))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblStatus))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBibliotekar;
    private javax.swing.JLabel lblBrStavki;
    private javax.swing.JLabel lblDatumIznajmljivanja;
    private javax.swing.JLabel lblRokVracanja;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tblStavkeIznajmljivanja;
    // End of variables declaration//GEN-END:variables

    private void ucitajStavkeIznajmljivanja() {
        StavkaIznajmljivanja stavkaZaPretragu = new StavkaIznajmljivanja();
        stavkaZaPretragu.setIznajmljivanje(izabranoIznajmljivanje);
        stavkeIznajmljivanja = communication.vratiSveStavkeIznajmljivanja(stavkaZaPretragu);
    }

    private void popuniTabelu() {
        TableModelStavkeIznajmljivanja model = new TableModelStavkeIznajmljivanja(stavkeIznajmljivanja);
        tblStavkeIznajmljivanja.setModel(model);
    }

    private void popuniOstalaPolja() {
        lblBibliotekar.setText(izabranoIznajmljivanje.getBibliotekar().toString());
        lblDatumIznajmljivanja.setText(izabranoIznajmljivanje.getDatumIznajmljivanja().format(DateTimeFormatter.ofPattern("dd.MM.yyyy")));
        lblRokVracanja.setText(izabranoIznajmljivanje.getRokVracanja().format(DateTimeFormatter.ofPattern("dd.MM.yyyy")));
        lblBrStavki.setText(String.valueOf(izabranoIznajmljivanje.getBrojStavkiIznajmljivanja()));
        lblStatus.setText(String.valueOf(izabranoIznajmljivanje.getStatus()));
    }
}
