/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme.knjiga;

import communication.Communication;
import javax.swing.JOptionPane;
import model.Knjiga;

/**
 *
 * @author kacan
 */
public class FrmDodajIzmeniKnjiga extends javax.swing.JFrame {

    Communication communication;
    FrmKnjige parent;
    Knjiga knjigaZaIzmenu;

    /**
     * Creates new form FrmDodajIzmeniKnjiga
     *
     * @param parent
     * @param knjiga
     */
    public FrmDodajIzmeniKnjiga(FrmKnjige parent, Knjiga knjiga) {
        this.parent = parent;
        this.knjigaZaIzmenu = knjiga;
        communication = Communication.getInstance();
        initComponents();
        if (knjigaZaIzmenu == null) {
            dodavanjeKnjige();
        } else {
            izmenaKnjige();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNaslov = new javax.swing.JTextField();
        txtISBN = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtIzdavac = new javax.swing.JTextField();
        btnDodaj = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnOdustani = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Naslov:");

        jLabel2.setText("ISBN:");

        jLabel3.setText("Autor:");

        jLabel4.setText("Izdavac:");

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(btnOdustani))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtISBN)
                            .addComponent(txtAutor)
                            .addComponent(txtIzdavac)
                            .addComponent(txtNaslov))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtIzdavac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnIzmeni)
                    .addComponent(btnOdustani))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        String naslov = txtNaslov.getText().trim();
        String isbn = txtISBN.getText().trim();
        String autor = txtAutor.getText().trim();
        String izdavac = txtIzdavac.getText().trim();

        if (naslov.isEmpty() || isbn.isEmpty() || autor.isEmpty() || izdavac.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sva polja moraju biti popunjena!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Knjiga novaKnjiga = new Knjiga(naslov, isbn, autor, izdavac);
        int uspeh = communication.dodajKnjigu(novaKnjiga);

        if (uspeh != 0) {
            JOptionPane.showMessageDialog(this, "Knjiga je uspešno dodata!", "Uspešno dodavanje", JOptionPane.INFORMATION_MESSAGE);
            parent.dobaviSveKnjige();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Došlo je do greške pri dodavanju knjige!", "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOdustaniActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        String naslov = txtNaslov.getText().trim();
        String isbn = txtISBN.getText().trim();
        String autor = txtAutor.getText().trim();
        String izdavac = txtIzdavac.getText().trim();

        if (naslov.isEmpty() || isbn.isEmpty() || autor.isEmpty() || izdavac.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sva polja moraju biti popunjena!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Knjiga izmenjenaKnjiga = new Knjiga(naslov, isbn, autor, izdavac);
        izmenjenaKnjiga.setIdKnjiga(knjigaZaIzmenu.getIdKnjiga());

        int uspeh = communication.izmeniKnjigu(izmenjenaKnjiga);

        if (uspeh != 0) {
            JOptionPane.showMessageDialog(this, "Knjiga je uspešno izmenjena.", "Uspešna izmena", JOptionPane.INFORMATION_MESSAGE);
            parent.dobaviSveKnjige();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Došlo je do greške pri izmeni knjige.", "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnOdustani;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtIzdavac;
    private javax.swing.JTextField txtNaslov;
    // End of variables declaration//GEN-END:variables

    private void dodavanjeKnjige() {
        setTitle("Dodavanje nove knjige");
        btnIzmeni.setVisible(false);
    }

    private void izmenaKnjige() {
        setTitle("Izmena knjige");
        btnDodaj.setVisible(false);
        txtNaslov.setText(knjigaZaIzmenu.getNaslov());
        txtISBN.setText(knjigaZaIzmenu.getIsbn());
        txtAutor.setText(knjigaZaIzmenu.getAutor());
        txtIzdavac.setText(knjigaZaIzmenu.getIzdavac());
    }
}
