/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import forme.clan.FrmClan;
import forme.knjiga.FrmKnjige;
import model.Bibliotekar;

/**
 *
 * @author kacan
 */
public class FrmBibliotekarGlavna extends javax.swing.JFrame {
    Bibliotekar ulogovani;

    /**
     * Creates new form FrmBibliotekarGlavna
     *
     * @param ulogovani
     */
    public FrmBibliotekarGlavna(Bibliotekar ulogovani) {
        this.ulogovani = ulogovani;
        initComponents();
        setTitle("Sistem za pracenje iznajmljivanja knjiga");
        popuniLabele();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblBibliotekar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnRadSaKnjigama = new javax.swing.JButton();
        lblSmena = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnRadSaClanovima = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bibliotekar:");

        lblBibliotekar.setText("Nevena Veljkovic");

        jLabel3.setText("Smena:");

        btnRadSaKnjigama.setText("Rad sa knjigama");
        btnRadSaKnjigama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadSaKnjigamaActionPerformed(evt);
            }
        });

        lblSmena.setText("PRVA");

        btnLogout.setText("Odjavi se");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnRadSaClanovima.setText("Rad sa clanovima");
        btnRadSaClanovima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadSaClanovimaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(btnRadSaKnjigama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblBibliotekar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                        .addComponent(btnLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSmena)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnRadSaClanovima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblBibliotekar)
                    .addComponent(btnLogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblSmena))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRadSaKnjigama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRadSaClanovima)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnRadSaKnjigamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadSaKnjigamaActionPerformed
        FrmKnjige frmKnjige = new FrmKnjige();
        frmKnjige.setVisible(true);
        frmKnjige.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnRadSaKnjigamaActionPerformed

    private void btnRadSaClanovimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadSaClanovimaActionPerformed
        FrmClan frmClan = new FrmClan();
        frmClan.setVisible(true);
        frmClan.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnRadSaClanovimaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRadSaClanovima;
    private javax.swing.JButton btnRadSaKnjigama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBibliotekar;
    private javax.swing.JLabel lblSmena;
    // End of variables declaration//GEN-END:variables

    private void popuniLabele() {
        lblBibliotekar.setText(ulogovani.toString());
    }
}
